/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gofact.presentacion.factura;

/**
 *
 * @author patricia
 */
public class DialogFacturas extends javax.swing.JDialog {

    /**
     * Creates new form DialogFacturas
     */
    public DialogFacturas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        grpDetalleGastos = new javax.swing.JPanel();
        lblAlimentacion = new javax.swing.JLabel();
        lblEducacion = new javax.swing.JLabel();
        lblVestimenta = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        lblVivienda = new javax.swing.JLabel();
        cmdMasAlimentacion = new javax.swing.JButton();
        cmdMenosAlimentacion = new javax.swing.JButton();
        lblEqTotalDeducibles = new javax.swing.JLabel();
        txtTotalAlimentacion = new javax.swing.JTextField();
        txtTotalEducacion = new javax.swing.JTextField();
        txtTotalSalud = new javax.swing.JTextField();
        txtTotalVivienda = new javax.swing.JTextField();
        txtTotalVestimenta = new javax.swing.JTextField();
        txtTotalOtrosGastos = new javax.swing.JTextField();
        lblOtrosGastos = new javax.swing.JLabel();
        lblEqTipoGasto = new javax.swing.JLabel();
        txtValAlimentacion = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        txtTotalEducacion1 = new javax.swing.JTextField();
        lblAlimentacion1 = new javax.swing.JLabel();
        grpTotales = new javax.swing.JPanel();
        lblEqDeducible = new javax.swing.JLabel();
        lblEqNoDeducible = new javax.swing.JLabel();
        lblEqTotalSinIVA = new javax.swing.JLabel();
        lblEqIVA = new javax.swing.JLabel();
        lblEqTotal = new javax.swing.JLabel();
        txtTotalDeducible = new javax.swing.JTextField();
        txtTotalNoDeducible = new javax.swing.JTextField();
        txtTotalSinIVA = new javax.swing.JTextField();
        txtIVA = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        grpInfoGeneral = new javax.swing.JPanel();
        lblEqNumFactura = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        lblEqFecha = new javax.swing.JLabel();
        dateFechaFactura = new com.toedter.calendar.JDateChooser();
        cmdComprobar = new javax.swing.JButton();
        grpInfoGeneral1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        gridProveedor = new javax.swing.JTable();
        txtRUCProveedor = new javax.swing.JTextField();
        cmdBuscarRUC = new javax.swing.JButton();
        lblEqDeducible1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gridFacturas = new javax.swing.JTable();
        lblTotalRegs = new javax.swing.JLabel();
        cmdNuevo = new javax.swing.JButton();
        cmdGuardar = new javax.swing.JButton();
        cmdCancelar = new javax.swing.JButton();
        cmdEditar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturas");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(90, 90));

        grpDetalleGastos.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de gastos"));

        lblAlimentacion.setText("Alimentación:");

        lblEducacion.setText("Educación:");

        lblVestimenta.setText("Vestimenta:");

        lblSalud.setText("Salud:");

        lblVivienda.setText("Vivienda:");

        cmdMasAlimentacion.setText("+");
        cmdMasAlimentacion.setEnabled(false);
        cmdMasAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMasAlimentacionActionPerformed(evt);
            }
        });

        cmdMenosAlimentacion.setText("-");
        cmdMenosAlimentacion.setEnabled(false);
        cmdMenosAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenosAlimentacionActionPerformed(evt);
            }
        });

        lblEqTotalDeducibles.setText("Total");

        txtTotalAlimentacion.setText("0.0");
        txtTotalAlimentacion.setEnabled(false);

        txtTotalEducacion.setText("0.0");
        txtTotalEducacion.setEnabled(false);

        txtTotalSalud.setText("0.0");
        txtTotalSalud.setEnabled(false);

        txtTotalVivienda.setText("0.0");
        txtTotalVivienda.setEnabled(false);

        txtTotalVestimenta.setText("0.0");
        txtTotalVestimenta.setEnabled(false);
        txtTotalVestimenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVestimentaActionPerformed(evt);
            }
        });

        txtTotalOtrosGastos.setText("0.0");
        txtTotalOtrosGastos.setEnabled(false);

        lblOtrosGastos.setText("Otros:");

        lblEqTipoGasto.setText("Rubros:");

        txtValAlimentacion.setText("0");
        txtValAlimentacion.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alimentación", "Educación", "Salud", "Vestimenta", "Vivienda", "Otros", " " }));

        txtTotalEducacion1.setText("0.0");
        txtTotalEducacion1.setEnabled(false);

        lblAlimentacion1.setText("Total por Rubros:");

        javax.swing.GroupLayout grpDetalleGastosLayout = new javax.swing.GroupLayout(grpDetalleGastos);
        grpDetalleGastos.setLayout(grpDetalleGastosLayout);
        grpDetalleGastosLayout.setHorizontalGroup(
            grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                        .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, grpDetalleGastosLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblEqTipoGasto)))
                        .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtValAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdMasAlimentacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdMenosAlimentacion)
                                .addGap(27, 27, 27)
                                .addComponent(txtTotalAlimentacion)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grpDetalleGastosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEqTotalDeducibles)
                                .addGap(41, 41, 41))))
                    .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                        .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAlimentacion)
                            .addComponent(lblSalud)
                            .addComponent(lblEducacion))
                        .addGap(18, 18, 18)
                        .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalEducacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 48, Short.MAX_VALUE)
                        .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                                .addComponent(lblOtrosGastos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalOtrosGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, grpDetalleGastosLayout.createSequentialGroup()
                                .addComponent(lblVivienda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTotalVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblVestimenta)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalVestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                        .addComponent(lblAlimentacion1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        grpDetalleGastosLayout.setVerticalGroup(
            grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grpDetalleGastosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEqTotalDeducibles)
                    .addComponent(lblEqTipoGasto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMasAlimentacion)
                    .addComponent(cmdMenosAlimentacion)
                    .addComponent(txtTotalAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAlimentacion1)
                .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalEducacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVestimenta)
                            .addComponent(txtTotalVestimenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(grpDetalleGastosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblAlimentacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEducacion)
                    .addComponent(txtTotalEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVivienda)
                    .addComponent(txtTotalVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grpDetalleGastosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalud)
                    .addComponent(txtTotalSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOtrosGastos)
                    .addComponent(txtTotalOtrosGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        lblOtrosGastos.getAccessibleContext().setAccessibleName("Otros:");

        grpTotales.setBorder(javax.swing.BorderFactory.createTitledBorder("Totales"));

        lblEqDeducible.setText("Deducible:");

        lblEqNoDeducible.setText("No deducible:");

        lblEqTotalSinIVA.setText("Total sin IVA:");

        lblEqIVA.setText("IVA (%):");

        lblEqTotal.setText("Total:");

        txtTotalDeducible.setText("0.0");
        txtTotalDeducible.setEnabled(false);
        txtTotalDeducible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDeducibleActionPerformed(evt);
            }
        });

        txtTotalNoDeducible.setText("0.0");
        txtTotalNoDeducible.setEnabled(false);
        txtTotalNoDeducible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalNoDeducibleActionPerformed(evt);
            }
        });

        txtTotalSinIVA.setEnabled(false);
        txtTotalSinIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalSinIVAActionPerformed(evt);
            }
        });

        txtIVA.setText("12");
        txtIVA.setEnabled(false);
        txtIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIVAActionPerformed(evt);
            }
        });

        txtTotal.setText("0.0");
        txtTotal.setEnabled(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grpTotalesLayout = new javax.swing.GroupLayout(grpTotales);
        grpTotales.setLayout(grpTotalesLayout);
        grpTotalesLayout.setHorizontalGroup(
            grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grpTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grpTotalesLayout.createSequentialGroup()
                        .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEqDeducible)
                            .addComponent(lblEqNoDeducible))
                        .addGap(10, 10, 10)
                        .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalNoDeducible)
                            .addComponent(txtTotalDeducible)))
                    .addGroup(grpTotalesLayout.createSequentialGroup()
                        .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEqIVA)
                            .addComponent(lblEqTotal)
                            .addComponent(lblEqTotalSinIVA))
                        .addGap(11, 11, 11)
                        .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalSinIVA)
                            .addComponent(txtIVA)
                            .addComponent(txtTotal))))
                .addGap(236, 236, 236))
        );
        grpTotalesLayout.setVerticalGroup(
            grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpTotalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEqDeducible)
                    .addComponent(txtTotalDeducible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEqNoDeducible)
                    .addComponent(txtTotalNoDeducible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEqTotalSinIVA)
                    .addComponent(txtTotalSinIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEqIVA)
                    .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grpTotalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEqTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grpInfoGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacíon general"));

        lblEqNumFactura.setText("N° factura:");

        txtNumFactura.setEnabled(false);
        txtNumFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFacturaActionPerformed(evt);
            }
        });

        lblEqFecha.setText("Fecha:");

        dateFechaFactura.setEnabled(false);

        cmdComprobar.setText("Comprobar");
        cmdComprobar.setEnabled(false);
        cmdComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprobarActionPerformed(evt);
            }
        });

        grpInfoGeneral1.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedor"));

        gridProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridProveedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(gridProveedor);

        txtRUCProveedor.setEnabled(false);

        cmdBuscarRUC.setText("Buscar");
        cmdBuscarRUC.setEnabled(false);
        cmdBuscarRUC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarRUCActionPerformed(evt);
            }
        });

        lblEqDeducible1.setText("RUC:");

        javax.swing.GroupLayout grpInfoGeneral1Layout = new javax.swing.GroupLayout(grpInfoGeneral1);
        grpInfoGeneral1.setLayout(grpInfoGeneral1Layout);
        grpInfoGeneral1Layout.setHorizontalGroup(
            grpInfoGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpInfoGeneral1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpInfoGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(grpInfoGeneral1Layout.createSequentialGroup()
                        .addComponent(lblEqDeducible1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRUCProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdBuscarRUC))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        grpInfoGeneral1Layout.setVerticalGroup(
            grpInfoGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpInfoGeneral1Layout.createSequentialGroup()
                .addGroup(grpInfoGeneral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRUCProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEqDeducible1)
                    .addComponent(cmdBuscarRUC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout grpInfoGeneralLayout = new javax.swing.GroupLayout(grpInfoGeneral);
        grpInfoGeneral.setLayout(grpInfoGeneralLayout);
        grpInfoGeneralLayout.setHorizontalGroup(
            grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpInfoGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grpInfoGeneral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(grpInfoGeneralLayout.createSequentialGroup()
                        .addGroup(grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEqNumFactura)
                            .addComponent(lblEqFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, grpInfoGeneralLayout.createSequentialGroup()
                                .addComponent(dateFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdComprobar)))
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addContainerGap())
        );
        grpInfoGeneralLayout.setVerticalGroup(
            grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grpInfoGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grpInfoGeneral1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEqNumFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(grpInfoGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEqFecha)
                    .addComponent(dateFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdComprobar))
                .addContainerGap())
        );

        gridFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gridFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gridFacturasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(gridFacturas);

        lblTotalRegs.setText("Total de registros: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grpTotales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grpDetalleGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalRegs)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(grpInfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(612, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalRegs)
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grpDetalleGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grpTotales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(grpInfoGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(627, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        cmdNuevo.setText("Nuevo");
        cmdNuevo.setName(""); // NOI18N
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });

        cmdGuardar.setText("Guardar");
        cmdGuardar.setEnabled(false);
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdCancelar.setText("Cancelar");
        cmdCancelar.setEnabled(false);
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdEditar.setText("Editar");
        cmdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditarActionPerformed(evt);
            }
        });

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(cmdGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdCancelar)
                        .addGap(230, 230, 230)
                        .addComponent(cmdEditar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdEliminar)
                        .addGap(0, 338, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdNuevo)
                    .addComponent(cmdGuardar)
                    .addComponent(cmdCancelar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmdEditar)
                        .addComponent(cmdEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalVestimentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVestimentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalVestimentaActionPerformed

    private void txtTotalDeducibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDeducibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDeducibleActionPerformed

    private void txtTotalNoDeducibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalNoDeducibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalNoDeducibleActionPerformed

    private void txtTotalSinIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalSinIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalSinIVAActionPerformed

    private void txtIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIVAActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtNumFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFacturaActionPerformed

    private void cmdComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprobarActionPerformed
        /*
        idLimite = obtenerIdLimiteGasto();
        switch(idLimite){
            case -1:
            JOptionPane.showMessageDialog(null, "No ha ingresado los límites de gasto para este año. Ingréselos e intente nuevamente.");
            break;
            case -2:
            JOptionPane.showMessageDialog(null, "Fecha incorrecta.");
            break;
            default:
            habilitarModificacionParte2(true);
            break;
        }
        */
    }//GEN-LAST:event_cmdComprobarActionPerformed

    private void gridProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridProveedorMouseClicked
        int fila = gridProveedor.rowAtPoint(evt.getPoint());
        //idProveedor = Integer.parseInt(gridProveedor.getValueAt(fila, 0).toString());
    }//GEN-LAST:event_gridProveedorMouseClicked

    private void cmdBuscarRUCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarRUCActionPerformed
        //mostrarProveedores(txtRUCProveedor.getText().trim(), "ruc");
    }//GEN-LAST:event_cmdBuscarRUCActionPerformed

    private void gridFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gridFacturasMouseClicked
        int fila = gridFacturas.rowAtPoint(evt.getPoint());
        //idFactura = Integer.parseInt(gridFacturas.getValueAt(fila, 0).toString());
        //idProveedor = Integer.parseInt(gridFacturas.getValueAt(fila, 2).toString());
        //idLimite = Integer.parseInt(gridFacturas.getValueAt(fila, 3).toString()); //comentr esta línea posteriormente
        txtNumFactura.setText(gridFacturas.getValueAt(fila, 4).toString());
        //dateFechaFactura.setDate(Date.valueOf(gridFacturas.getValueAt(fila, 5).toString()));
        txtTotalAlimentacion.setText(gridFacturas.getValueAt(fila, 6).toString());
        txtTotalEducacion.setText(gridFacturas.getValueAt(fila, 7).toString());
        txtTotalSalud.setText(gridFacturas.getValueAt(fila, 8).toString());
        txtTotalVestimenta.setText(gridFacturas.getValueAt(fila, 9).toString());
        txtTotalVivienda.setText(gridFacturas.getValueAt(fila, 10).toString());
        txtTotalOtrosGastos.setText(gridFacturas.getValueAt(fila, 11).toString());
       // txtTotalGastoNegocio.setText(gridFacturas.getValueAt(fila, 12).toString());
        txtTotalSinIVA.setText(gridFacturas.getValueAt(fila, 13).toString());
        txtIVA.setText(gridFacturas.getValueAt(fila, 14).toString());
        txtTotal.setText(gridFacturas.getValueAt(fila, 15).toString());
    }//GEN-LAST:event_gridFacturasMouseClicked

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
        /*
        limpiar();
        accion = "nuevo";
        habilitarModificacionParte1(true);
        */
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        /*
        DatosFactura df = new DatosFactura();
        TablaFactura tf = new TablaFactura();
        idLimite = obtenerIdLimiteGasto();
        if (idLimite < 0){
            JOptionPane.showMessageDialog(null, "No ha ingresado los límites de gasto para este año. Ingréselos e intente nuevamente.");
            return;
        }
        df.IdFactura = idFactura;
        df.IdUsuario = idUsuario;
        df.IdProveedor = idProveedor;
        df.IdLimite = idLimite;
        df.Numero = txtNumFactura.getText().trim();
        df.Fecha = new java.sql.Date(dateFechaFactura.getDate().getTime());
        df.SumAlimentacion = Double.parseDouble(txtTotalAlimentacion.getText().trim());
        df.SumEducacion = Double.parseDouble(txtTotalEducacion.getText().trim());
        df.SumSalud = Double.parseDouble(txtTotalSalud.getText().trim());
        df.SumVestido = Double.parseDouble(txtTotalVestimenta.getText().trim());
        df.SumVivienda = Double.parseDouble(txtTotalVivienda.getText().trim());
        df.SumOtros = Double.parseDouble(txtTotalOtrosGastos.getText().trim());
        df.SumGastosNegocio = Double.parseDouble(txtTotalGastoNegocio.getText().trim());
        df.TotalSinIVA = Double.parseDouble(txtTotalSinIVA.getText().trim());
        df.IVA = Double.parseDouble(txtIVA.getText().trim());
        df.Total = Double.parseDouble(txtTotal.getText().trim());
        boolean resultado = false;
        switch (accion) {
            case "nuevo":
            resultado = tf.insertar(df);
            break;
            case "editar":
            resultado = tf.editar(df);
            break;
        }
        if (resultado){
            JOptionPane.showMessageDialog(null, "Operación completada");
            habilitarModificacionParte1(false);
            habilitarModificacionParte2(false);
            limpiar();
            mostrar();
        } else {
            JOptionPane.showMessageDialog(null, "Error. La operación no ha podido ser ejecutada");
        }
        */
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        /*
        habilitarModificacionParte1(false);
        habilitarModificacionParte2(false);
        limpiar();
        accion = "";
        */
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditarActionPerformed
        /*
        if (idFactura != -1) {
            accion = "editar";
            habilitarModificacionParte1(true);
            mostrarProveedores(Integer.toString(idProveedor), "id");
            habilitarModificacionParte2(true);
        }
        */
    }//GEN-LAST:event_cmdEditarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        /*
        if (idFactura != -1) {
            if (JOptionPane.showConfirmDialog(rootPane, "Seguro de eliminar", "Confirmar", 2) == 0){
                TablaFactura tf = new TablaFactura();
                DatosFactura df = new DatosFactura();
                df.IdFactura = idFactura;
                if (tf.eliminar(df)){
                    JOptionPane.showMessageDialog(null, "Operación completada");
                    limpiar();
                    mostrar();
                } else {
                    JOptionPane.showMessageDialog(null, "Error. La operación no ha podido ser ejecutada");
                }
            }
        }
        */
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdMenosAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenosAlimentacionActionPerformed
        /*
        if (validarCajas(txtValAlimentacion.getText())){
            double resto = Double.parseDouble(txtTotalAlimentacion.getText()) - Double.parseDouble(txtValAlimentacion.getText());
            if (resto < 0) resto = 0;
            txtTotalAlimentacion.setText(String.valueOf(resto));
            calcularTotalDeducible();
        }
        txtValAlimentacion.setText("0");
        */
    }//GEN-LAST:event_cmdMenosAlimentacionActionPerformed

    private void cmdMasAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMasAlimentacionActionPerformed
        /*
        if (validarCajas(txtValAlimentacion.getText()))
        txtTotalAlimentacion.setText(String.valueOf(Double.parseDouble(txtTotalAlimentacion.getText()) + Double.parseDouble(txtValAlimentacion.getText())));
        txtValAlimentacion.setText("0");
        calcularTotalDeducible();
        */
    }//GEN-LAST:event_cmdMasAlimentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFacturas dialog = new DialogFacturas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBuscarRUC;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdComprobar;
    private javax.swing.JButton cmdEditar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdMasAlimentacion;
    private javax.swing.JButton cmdMenosAlimentacion;
    private javax.swing.JButton cmdNuevo;
    private com.toedter.calendar.JDateChooser dateFechaFactura;
    private javax.swing.JTable gridFacturas;
    private javax.swing.JTable gridProveedor;
    private javax.swing.JPanel grpDetalleGastos;
    private javax.swing.JPanel grpInfoGeneral;
    private javax.swing.JPanel grpInfoGeneral1;
    private javax.swing.JPanel grpTotales;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlimentacion;
    private javax.swing.JLabel lblAlimentacion1;
    private javax.swing.JLabel lblEducacion;
    private javax.swing.JLabel lblEqDeducible;
    private javax.swing.JLabel lblEqDeducible1;
    private javax.swing.JLabel lblEqFecha;
    private javax.swing.JLabel lblEqIVA;
    private javax.swing.JLabel lblEqNoDeducible;
    private javax.swing.JLabel lblEqNumFactura;
    private javax.swing.JLabel lblEqTipoGasto;
    private javax.swing.JLabel lblEqTotal;
    private javax.swing.JLabel lblEqTotalDeducibles;
    private javax.swing.JLabel lblEqTotalSinIVA;
    private javax.swing.JLabel lblOtrosGastos;
    private javax.swing.JLabel lblSalud;
    private javax.swing.JLabel lblTotalRegs;
    private javax.swing.JLabel lblVestimenta;
    private javax.swing.JLabel lblVivienda;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtRUCProveedor;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalAlimentacion;
    private javax.swing.JTextField txtTotalDeducible;
    private javax.swing.JTextField txtTotalEducacion;
    private javax.swing.JTextField txtTotalEducacion1;
    private javax.swing.JTextField txtTotalNoDeducible;
    private javax.swing.JTextField txtTotalOtrosGastos;
    private javax.swing.JTextField txtTotalSalud;
    private javax.swing.JTextField txtTotalSinIVA;
    private javax.swing.JTextField txtTotalVestimenta;
    private javax.swing.JTextField txtTotalVivienda;
    private javax.swing.JTextField txtValAlimentacion;
    // End of variables declaration//GEN-END:variables
}
