/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gofact.presentacion;

/**
 *
 * @author camm
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuProveedor = new javax.swing.JMenu();
        menuItemConsultarProveedor = new javax.swing.JMenuItem();
        menuFactura = new javax.swing.JMenu();
        menuItemConsultarFactura = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuItemObtenerReporte = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuItemModificarUsuario = new javax.swing.JMenuItem();
        menuItemModificarEliminar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemManual = new javax.swing.JMenuItem();
        menuItemAcerca = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );

        menuProveedor.setText("Proveedor");

        menuItemConsultarProveedor.setText("Consultar");
        menuItemConsultarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarProveedorActionPerformed(evt);
            }
        });
        menuProveedor.add(menuItemConsultarProveedor);

        menuBarPrincipal.add(menuProveedor);

        menuFactura.setText("Factura");

        menuItemConsultarFactura.setText("Consultar");
        menuFactura.add(menuItemConsultarFactura);

        menuBarPrincipal.add(menuFactura);

        menuReportes.setText("Reportes");

        menuItemObtenerReporte.setText("Obtener");
        menuReportes.add(menuItemObtenerReporte);

        menuBarPrincipal.add(menuReportes);

        menuUsuario.setText("Usuario");

        menuItemModificarUsuario.setText("Modificar");
        menuUsuario.add(menuItemModificarUsuario);

        menuItemModificarEliminar.setText("Eliminar");
        menuUsuario.add(menuItemModificarEliminar);

        menuBarPrincipal.add(menuUsuario);

        menuAyuda.setText("Ayuda");

        menuItemManual.setText("Manual");
        menuAyuda.add(menuItemManual);

        menuItemAcerca.setText("Acerca ...");
        menuAyuda.add(menuItemAcerca);

        menuBarPrincipal.add(menuAyuda);

        menuCerrarSesion.setText("Cerrar Sesión");
        menuBarPrincipal.add(menuCerrarSesion);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemConsultarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemConsultarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenuItem menuItemAcerca;
    private javax.swing.JMenuItem menuItemConsultarFactura;
    private javax.swing.JMenuItem menuItemConsultarProveedor;
    private javax.swing.JMenuItem menuItemManual;
    private javax.swing.JMenuItem menuItemModificarEliminar;
    private javax.swing.JMenuItem menuItemModificarUsuario;
    private javax.swing.JMenuItem menuItemObtenerReporte;
    private javax.swing.JMenu menuProveedor;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuario;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
