/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gofact.presentacion;

import com.gofact.presentacion.factura.DialogExportarXML;
import com.gofact.presentacion.factura.DialogFacturas;
import com.gofact.presentacion.factura.DialogInsertarFactura;
import com.gofact.presentacion.proveedores.DialogInsertar;
import com.gofact.presentacion.proveedores.DialogProv;
import com.gofact.presentacion.reportes.DialogGenerarReporte;
import com.gofact.presentacion.usuarios.DialogEditarInformacionUsuario;
import com.gofact.presentacion.usuarios.DialogEliminarUsuario;

/**
 *
 * @author camm
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBarPrincipal = new javax.swing.JMenuBar();
        menuProveedor = new javax.swing.JMenu();
        menuItemConsultarProveedor = new javax.swing.JMenuItem();
        menuFactura = new javax.swing.JMenu();
        menuItemConsultarFactura = new javax.swing.JMenuItem();
        menuItemExportarXML = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        menuItemObtenerReporte = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuItemModificarUsuario = new javax.swing.JMenuItem();
        menuItemModificarEliminar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuItemAcerca = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenu();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemCerrarSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GoFact!");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Bienvenido: Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(263, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        menuProveedor.setText("Proveedor");

        menuItemConsultarProveedor.setText("Consultar");
        menuItemConsultarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarProveedorActionPerformed(evt);
            }
        });
        menuProveedor.add(menuItemConsultarProveedor);

        menuBarPrincipal.add(menuProveedor);

        menuFactura.setText("Factura");

        menuItemConsultarFactura.setText("Consultar");
        menuItemConsultarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarFacturaActionPerformed(evt);
            }
        });
        menuFactura.add(menuItemConsultarFactura);

        menuItemExportarXML.setText("Exportar XML");
        menuItemExportarXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExportarXMLActionPerformed(evt);
            }
        });
        menuFactura.add(menuItemExportarXML);

        menuBarPrincipal.add(menuFactura);

        menuReportes.setText("Reportes");

        menuItemObtenerReporte.setText("Obtener");
        menuItemObtenerReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemObtenerReporteActionPerformed(evt);
            }
        });
        menuReportes.add(menuItemObtenerReporte);

        menuBarPrincipal.add(menuReportes);

        menuUsuario.setText("Usuario");

        menuItemModificarUsuario.setText("Modificar");
        menuItemModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemModificarUsuario);

        menuItemModificarEliminar.setText("Eliminar");
        menuItemModificarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModificarEliminarActionPerformed(evt);
            }
        });
        menuUsuario.add(menuItemModificarEliminar);

        menuBarPrincipal.add(menuUsuario);

        menuAyuda.setText("Ayuda");

        menuItemAcerca.setText("Acerca ...");
        menuItemAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAcercaActionPerformed(evt);
            }
        });
        menuAyuda.add(menuItemAcerca);

        menuBarPrincipal.add(menuAyuda);

        menuCerrarSesion.setText("Salir");
        menuCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarSesionMouseClicked(evt);
            }
        });
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });

        menuItemCerrarSesion.setText("Cerrar Sesión");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        menuCerrarSesion.add(menuItemCerrarSesion);

        menuItemCerrarSistema.setText("Cerrar Sistema");
        menuItemCerrarSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSistemaActionPerformed(evt);
            }
        });
        menuCerrarSesion.add(menuItemCerrarSistema);

        menuBarPrincipal.add(menuCerrarSesion);

        setJMenuBar(menuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemConsultarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarProveedorActionPerformed
        DialogProv dialogProv = new DialogProv(this, true);
        dialogProv.setVisible(true);
    }//GEN-LAST:event_menuItemConsultarProveedorActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        this.dispose();
        FrmInicioSesion frmInicioSesion = new FrmInicioSesion();
        frmInicioSesion.setVisible(true);
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    private void menuItemConsultarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarFacturaActionPerformed
        // TODO add your handling code here:
        DialogInsertarFactura dialogInsertarFactura = new DialogInsertarFactura(this, true);
        dialogInsertarFactura.setVisible(true);
    }//GEN-LAST:event_menuItemConsultarFacturaActionPerformed

    private void menuItemObtenerReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemObtenerReporteActionPerformed
        // TODO add your handling code here:
        DialogGenerarReporte dialogGenerarReporte = new DialogGenerarReporte(this, true);
        dialogGenerarReporte.setVisible(true);
    }//GEN-LAST:event_menuItemObtenerReporteActionPerformed

    private void menuItemModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarUsuarioActionPerformed
        DialogEditarInformacionUsuario deiu = new DialogEditarInformacionUsuario(this, true);
        deiu.setVisible(true);
    }//GEN-LAST:event_menuItemModificarUsuarioActionPerformed

    private void menuItemModificarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModificarEliminarActionPerformed
        DialogEliminarUsuario deu = new DialogEliminarUsuario(this, true);
        deu.setVisible(true);
    }//GEN-LAST:event_menuItemModificarEliminarActionPerformed

    private void menuItemAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAcercaActionPerformed
        DialogAbout about = new DialogAbout(this, true);
        about.setVisible(true);
    }//GEN-LAST:event_menuItemAcercaActionPerformed

    private void menuCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarSesionMouseClicked

    }//GEN-LAST:event_menuCerrarSesionMouseClicked

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        this.dispose();
        FrmInicioSesion frmInicioSesion = new FrmInicioSesion();
        frmInicioSesion.setVisible(true);
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemCerrarSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSistemaActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuItemCerrarSistemaActionPerformed

    private void menuItemExportarXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExportarXMLActionPerformed
        DialogExportarXML dexml = new DialogExportarXML(this, true);
        dexml.setVisible(true);
    }//GEN-LAST:event_menuItemExportarXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBarPrincipal;
    private javax.swing.JMenu menuCerrarSesion;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenuItem menuItemAcerca;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemCerrarSistema;
    private javax.swing.JMenuItem menuItemConsultarFactura;
    private javax.swing.JMenuItem menuItemConsultarProveedor;
    private javax.swing.JMenuItem menuItemExportarXML;
    private javax.swing.JMenuItem menuItemModificarEliminar;
    private javax.swing.JMenuItem menuItemModificarUsuario;
    private javax.swing.JMenuItem menuItemObtenerReporte;
    private javax.swing.JMenu menuProveedor;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
